/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'FlightController.Debug+STM32F411CEUx' 
 * Target:  'Debug+STM32F411CEUx' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f4xx.h"

/* Keil::Device:Startup@2.1.0 */
#define RTE_DEVICE_STARTUP_STM32F4XX    /* Device Startup for STM32F4 */


#endif /* RTE_COMPONENTS_H */
